from importlib.metadata import (
    PackageNotFoundError as _PackageNotFoundError,
    version as _distribution_version,
)

from .assembler import NativeAssembler
from .basis import (
    Basis,
    DiscreteField,
    DofsView,
    ElementHex1,
    ElementHex2,
    ElementHex0,
    ElementDG,
    ElementQuad1,
    ElementQuad2,
    ElementQuad0,
    ElementComposite,
    ElementTriP1,
    ElementTriP2,
    ElementTriP0,
    ElementTetP1,
    ElementTetP2,
    ElementTetP0,
    ElementWedge1,
    ElementPyramid1,
    ElementVector,
    FacetBasis,
    InteriorFacetBasis,
    MeshHex,
    MeshHex2,
    MeshQuad,
    MeshQuad2,
    MeshTri,
    MeshTri2,
    MeshTet,
    MeshTet2,
    MeshWedge1,
    MeshPyramid1,
)
from .evaluation import EvaluationDiagnostics, NativeEvaluation
from .linear_form import LinearFormDiagnostics, NativeLinearForm
from .bilinear_form import NativeBilinearForm
from .supermesh import (
    MortarCouplingResult,
    MortarTraceData,
    SupermeshDiagnostics,
    SupermeshSearch,
    TriangleSupermesh,
)
from .interface import InterfaceField
from .forms import (
    BilinearForm,
    Functional,
    LinearForm,
    UnsupportedNativeForm,
    asm,
)
from .kernels import (
    LinearElasticHex8,
    LinearElasticTet4,
    LinearElasticity,
    NeoHookean,
    NeoHookeanHex8,
    NeoHookeanTet4,
)
from .runtime import (
    BACKEND,
    CAPABILITIES,
    available_num_threads,
    get_num_threads,
    has_capability,
    set_num_threads,
    thread_limit,
)
from .material import (
    J2Assembler,J2Evaluation,J2Plasticity,J2State,MaterialAssembler,
    MaterialState,
    StandardLinearSolid,StandardLinearSolidEvaluation,
    StandardLinearSolidState,
)

try:
    __version__=_distribution_version("skfem-native")
except _PackageNotFoundError:
    __version__="0+unknown"

__all__ = [
    "__version__",
    "BACKEND",
    "CAPABILITIES",
    "available_num_threads",
    "get_num_threads",
    "has_capability",
    "set_num_threads",
    "thread_limit",
    "EvaluationDiagnostics",
    "LinearElasticTet4",
    "LinearElasticHex8",
    "LinearElasticity",
    "LinearFormDiagnostics",
    "J2Evaluation",
    "J2Assembler",
    "J2Plasticity",
    "J2State",
    "MaterialAssembler",
    "MaterialState",
    "StandardLinearSolid",
    "StandardLinearSolidEvaluation",
    "StandardLinearSolidState",
    "NativeAssembler",
    "NativeEvaluation",
    "NativeLinearForm",
    "NativeBilinearForm",
    "LinearForm",
    "Functional",
    "BilinearForm",
    "Basis",
    "DiscreteField",
    "DofsView",
    "ElementTetP1",
    "ElementTetP2",
    "ElementTetP0",
    "ElementWedge1",
    "ElementPyramid1",
    "ElementHex1",
    "ElementHex2",
    "ElementHex0",
    "ElementDG",
    "ElementQuad1",
    "ElementQuad2",
    "ElementQuad0",
    "ElementComposite",
    "ElementTriP1",
    "ElementTriP2",
    "ElementTriP0",
    "ElementVector",
    "FacetBasis",
    "InteriorFacetBasis",
    "MeshTet",
    "MeshTet2",
    "MeshWedge1",
    "MeshPyramid1",
    "MeshHex",
    "MeshHex2",
    "MeshQuad",
    "MeshQuad2",
    "MeshTri",
    "MeshTri2",
    "asm",
    "UnsupportedNativeForm",
    "TriangleSupermesh",
    "MortarCouplingResult",
    "MortarTraceData",
    "SupermeshDiagnostics",
    "SupermeshSearch",
    "InterfaceField",
    "NeoHookeanTet4",
    "NeoHookeanHex8",
    "NeoHookean",
]
