from importlib.metadata import (
    PackageNotFoundError as _PackageNotFoundError,
    version as _distribution_version,
)

from .basis import (
    Basis,
    DiscreteField,
    DofsView,
    GeometryDiagnostics,
    ElementHex1,
    ElementHex2,
    ElementHex20,
    ElementHex0,
    ElementDG,
    ElementQuad1,
    ElementQuad2,
    ElementQuad8,
    ElementQuad0,
    ElementComposite,
    ElementTriP1,
    ElementTriP2,
    ElementTriP0,
    ElementTetP1,
    ElementTetP2,
    ElementTetP0,
    ElementWedge1,
    ElementPyramid1,
    ElementVector,
    FacetBasis,
    InteriorFacetBasis,
    MeshHex,
    MeshHex2,
    MeshHex20,
    MeshQuad,
    MeshQuad2,
    MeshQuad8,
    MeshTri,
    MeshTri2,
    MeshTet,
    MeshTet2,
    MeshWedge1,
    MeshPyramid1,
)
from .linear_form import LinearFormDiagnostics, NativeLinearForm
from .bilinear_form import NativeBilinearForm, NativeCrossBilinearForm
from .supermesh import (
    CrossTabulation,
    InterfaceSupermesh,
    ContactFacetSearchResult,
    MortarTraceData,
    SupermeshDiagnostics,
    SupermeshSearch,
    TriangleSupermesh,
    contact_projection_tolerance,
    find_contact_facets,
)
from .interface import InterfaceField
from .regions import (
    CellRegion,EntityRegion,FacetRegion,NodeRegion,RegionDiagnostics,
)
from .levelset import (
    CellClassification,CellClassificationResult,CutCellQuadrature,
    CutQuadratureDiagnostics,ImplicitInterfaceQuadrature,
    LevelSet,LevelSetDiagnostics,
)
from .cut_basis import CutCellBasis,ImplicitFacetBasis
from .implicit_interface import ImplicitInterfacePair
from .forms import (
    BilinearForm,
    Functional,
    LinearForm,
    UnsupportedNativeForm,
    asm,
)
from .runtime import (
    BACKEND,
    CAPABILITIES,
    available_num_threads,
    get_num_threads,
    has_capability,
    set_num_threads,
    thread_limit,
)
from .capabilities import (
    CAPABILITY_REGISTRY,
    Capability,
    CapabilityStatus,
    UnsupportedCapabilityError,
    capabilities,
    get_capability,
    require_capability,
    supports,
)
from .preflight import (
    AssemblyMemoryBudgetError,
    AssemblyMemoryEstimate,
    CompositeAssemblyMemoryEstimate,
    estimate_bilinear_memory,
    estimate_composite_bilinear_memory,
    enforce_memory_budget,
    format_bytes,
)
from .hcurl_basis import (
    AffineTetN1Basis,AffineTriN1Basis,
    HcurlGeometryDiagnostics,HcurlTetGeometryDiagnostics,
)
from .hcurl_assembler import (
    TriN1Assembler,
    TriN1LinearAssembler,
    estimate_tri_n1_assembly_memory,
)

try:
    __version__=_distribution_version("skfem-native")
except _PackageNotFoundError:
    __version__="0+unknown"

__all__ = [
    "__version__",
    "BACKEND",
    "CrossTabulation",
    "NativeCrossBilinearForm",
    "CAPABILITIES",
    "available_num_threads",
    "get_num_threads",
    "has_capability",
    "set_num_threads",
    "thread_limit",
    "CAPABILITY_REGISTRY",
    "Capability",
    "CapabilityStatus",
    "UnsupportedCapabilityError",
    "capabilities",
    "get_capability",
    "require_capability",
    "supports",
    "AssemblyMemoryEstimate",
    "AssemblyMemoryBudgetError",
    "CompositeAssemblyMemoryEstimate",
    "estimate_bilinear_memory",
    "estimate_composite_bilinear_memory",
    "enforce_memory_budget",
    "format_bytes",
    "AffineTriN1Basis",
    "AffineTetN1Basis",
    "HcurlGeometryDiagnostics",
    "HcurlTetGeometryDiagnostics",
    "TriN1Assembler",
    "TriN1LinearAssembler",
    "estimate_tri_n1_assembly_memory",
    "LinearFormDiagnostics",
    "NativeLinearForm",
    "NativeBilinearForm",
    "LinearForm",
    "Functional",
    "BilinearForm",
    "Basis",
    "DiscreteField",
    "DofsView",
    "GeometryDiagnostics",
    "ElementTetP1",
    "ElementTetP2",
    "ElementTetP0",
    "ElementWedge1",
    "ElementPyramid1",
    "ElementHex1",
    "ElementHex2",
    "ElementHex20",
    "ElementHex0",
    "ElementDG",
    "ElementQuad1",
    "ElementQuad2",
    "ElementQuad8",
    "ElementQuad0",
    "ElementComposite",
    "ElementTriP1",
    "ElementTriP2",
    "ElementTriP0",
    "ElementVector",
    "FacetBasis",
    "InteriorFacetBasis",
    "MeshTet",
    "MeshTet2",
    "MeshWedge1",
    "MeshPyramid1",
    "MeshHex",
    "MeshHex2",
    "MeshHex20",
    "MeshQuad",
    "MeshQuad2",
    "MeshQuad8",
    "MeshTri",
    "MeshTri2",
    "asm",
    "UnsupportedNativeForm",
    "TriangleSupermesh",
    "InterfaceSupermesh",
    "ContactFacetSearchResult",
    "contact_projection_tolerance",
    "find_contact_facets",
    "MortarTraceData",
    "SupermeshDiagnostics",
    "SupermeshSearch",
    "InterfaceField",
    "EntityRegion",
    "CellRegion",
    "FacetRegion",
    "NodeRegion",
    "RegionDiagnostics",
    "CellClassification",
    "CellClassificationResult",
    "CutCellQuadrature",
    "CutQuadratureDiagnostics",
    "CutCellBasis",
    "ImplicitInterfaceQuadrature",
    "ImplicitFacetBasis",
    "ImplicitInterfacePair",
    "LevelSet",
    "LevelSetDiagnostics",
]
